export const INITIAL_PROJECTS = [
  {
    id: 1,
    priority: 7,
    priorityColor: "green", // green, yellow, orange, red
    name: "AEON LONG BIÊN",
    client: "AEON",
    pm: "Lê Văn C.",
    sm: "Bùi M. T.",
    capacity: 1000,
    progress: 70,
    deviation: 3.10, // positive
    codDays: 95,
    codDate: "23/06/2026",
    risk: "LOW", // LOW, MEDIUM, HIGH
    issue: "Không có",
    issueType: "none", // none, warning, danger, medium
    lastUpdated: "1 ngày trước",
    status: "in_progress", // in_progress, completed
    region: "Miền Bắc",
  },
  {
    id: 2,
    priority: 8,
    priorityColor: "green",
    name: "CANIFA HCM",
    client: "CANIFA",
    pm: "Lê Văn C.",
    sm: "Nguyễn V. K.",
    capacity: 600,
    progress: 72,
    deviation: 4.50,
    codDays: 110,
    codDate: "07/09/2026",
    risk: "LOW",
    issue: "Không có",
    issueType: "none",
    lastUpdated: "1 ngày trước",
    status: "in_progress",
    region: "Miền Nam",
  },
  {
    id: 3,
    priority: 5,
    priorityColor: "green",
    name: "SG3 - GD 2",
    client: "SUNTORY",
    pm: "Trần Văn A.",
    sm: "Nguyễn T. D.",
    capacity: 1500,
    progress: 62,
    deviation: 1.20,
    codDays: 72,
    codDate: "31/07/2026",
    risk: "LOW",
    issue: "Không có",
    issueType: "none",
    lastUpdated: "3 giờ trước",
    status: "in_progress",
    region: "Miền Nam",
  },
  {
    id: 4,
    priority: 4,
    priorityColor: "yellow",
    name: "MENTO",
    client: "MENTOS",
    pm: "Nguyễn H.",
    sm: "Đỗ Văn C.",
    capacity: 1200,
    progress: 55,
    deviation: -2.20,
    codDays: 55,
    codDate: "14/07/2026",
    risk: "LOW",
    issue: "Thời tiết mưa nhiều",
    issueType: "medium",
    lastUpdated: "2 giờ trước",
    status: "in_progress",
    region: "Miền Trung",
  },
  {
    id: 5,
    priority: 6,
    priorityColor: "green",
    name: "FPT CT",
    client: "FPT",
    pm: "Phạm Văn B.",
    sm: "Hoàng A.",
    capacity: 800,
    progress: 58,
    deviation: 0.50,
    codDays: 80,
    codDate: "08/08/2026",
    risk: "LOW",
    issue: "Không có",
    issueType: "none",
    lastUpdated: "4 giờ trước",
    status: "in_progress",
    region: "Miền Nam",
  },
  {
    id: 6,
    priority: 1,
    priorityColor: "red",
    name: "VAL",
    client: "PEPSICO",
    pm: "Nguyễn H.",
    sm: "Võ Minh Q.",
    capacity: 1000,
    progress: 42,
    deviation: -5.45,
    codDays: 40,
    codDate: "29/06/2026",
    risk: "HIGH",
    issue: "Thiếu vật tư rail",
    issueType: "danger",
    lastUpdated: "2 giờ trước",
    status: "in_progress",
    region: "Miền Nam",
  },
  {
    id: 7,
    priority: 2,
    priorityColor: "orange",
    name: "OSAKA",
    client: "PEPSICO",
    pm: "Trần Văn A.",
    sm: "Nguyễn Đ. T.",
    capacity: 500,
    progress: 45,
    deviation: -5.00,
    codDays: 41,
    codDate: "30/06/2026",
    risk: "MEDIUM",
    issue: "Khách hàng chậm approve",
    issueType: "orange",
    lastUpdated: "5 giờ trước",
    status: "in_progress",
    region: "Miền Trung",
  },
  {
    id: 8,
    priority: 3,
    priorityColor: "orange",
    name: "YUSEN",
    client: "PEPSICO",
    pm: "Phạm Văn B.",
    sm: "Lê Xuân H.",
    capacity: 500,
    progress: 45,
    deviation: -5.00,
    codDays: 41,
    codDate: "30/06/2026",
    risk: "MEDIUM",
    issue: "Inverter chưa về",
    issueType: "orange",
    lastUpdated: "1 ngày trước",
    status: "in_progress",
    region: "Miền Trung",
  },
  // Projects for Page 2 & summing to KPIs
  {
    id: 9,
    priority: 10,
    priorityColor: "green",
    name: "LOTTE MALL HÀ NỘI",
    client: "LOTTE",
    pm: "Lê Văn C.",
    sm: "Bùi M. T.",
    capacity: 5000,
    progress: 100,
    deviation: 0.00,
    codDays: 0,
    codDate: "15/01/2026",
    risk: "LOW",
    issue: "Không có",
    issueType: "none",
    lastUpdated: "1 tuần trước",
    status: "completed",
    region: "Miền Bắc",
  },
  {
    id: 10,
    priority: 11,
    priorityColor: "green",
    name: "VINHOMES OCEAN PARK",
    client: "VINGROUP",
    pm: "Nguyễn H.",
    sm: "Đỗ Văn C.",
    capacity: 3000,
    progress: 100,
    deviation: 1.50,
    codDays: 0,
    codDate: "10/02/2026",
    risk: "LOW",
    issue: "Không có",
    issueType: "none",
    lastUpdated: "2 tuần trước",
    status: "completed",
    region: "Miền Bắc",
  },
  {
    id: 11,
    priority: 12,
    priorityColor: "green",
    name: "SÂN BAY LONG THÀNH GD1",
    client: "ACV",
    pm: "Trần Văn A.",
    sm: "Nguyễn T. D.",
    capacity: 3000,
    progress: 100,
    deviation: 2.00,
    codDays: 0,
    codDate: "05/03/2026",
    risk: "LOW",
    issue: "Không có",
    issueType: "none",
    lastUpdated: "3 tuần trước",
    status: "completed",
    region: "Miền Nam",
  },
  {
    id: 12,
    priority: 9,
    priorityColor: "green",
    name: "SABECO BÌNH DƯƠNG",
    client: "SABECO",
    pm: "Phạm Văn B.",
    sm: "Hoàng A.",
    capacity: 800,
    progress: 15,
    deviation: -1.50,
    codDays: 180,
    codDate: "15/11/2026",
    risk: "LOW",
    issue: "Không có",
    issueType: "none",
    lastUpdated: "5 ngày trước",
    status: "in_progress",
    region: "Miền Nam",
  }
];
